version: 0.0
os: linux
files:
   - source: /target
     destination: /opt/jetty/current/webapps/
hooks:
   ApplicationStop:
     - location: scripts/stop.sh
   AfterInstall:
    - location: scripts/copywar.sh
   ApplicationStart:
   - location: scripts/start.sh
